package io.sinapsi.hive.cli.c4.writer;

import java.util.List;

/**
 * Generates {@code docs/architecture/index.html}: a static, dependency-free page that shows the
 * generated diagrams, explains the C4 levels, and visualises Hive's hexagonal flow. This is the
 * first thing a developer sees — it is meant to produce a "wow" moment worth screenshotting.
 */
public final class ArchitectureSiteWriter {

    /** One diagram shown on the page. {@code inlineSvg} is the SVG markup (already stripped of its
     * XML prolog) when an SVG render exists; otherwise it is {@code null} and {@code imageFileName}
     * (an SVG or PNG) is linked, or only the source link is shown. */
    public record DiagramEntry(String displayName, String pumlFileName, String imageFileName, String inlineSvg) {
    }

    public String fileName() {
        return "index.html";
    }

    /** Removes a leading {@code <?xml ...?>} prolog / DOCTYPE so the SVG can be inlined into HTML. */
    public static String stripSvgProlog(String svg) {
        if (svg == null) {
            return null;
        }
        int start = svg.indexOf("<svg");
        return start <= 0 ? svg : svg.substring(start);
    }

    public String render(String projectName, String basePackage, String timestamp, List<DiagramEntry> entries) {
        StringBuilder body = new StringBuilder();
        body.append("""
                <!DOCTYPE html>
                <html lang="en">
                <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <title>%s — Hive Architecture Map</title>
                <style>
                %s
                </style>
                </head>
                <body>
                <div class="page">
                """.formatted(escape(projectName), css()));

        body.append("""
                  <header class="hero">
                    <div class="brand">🐝 Hive</div>
                    <h1>Architecture Map</h1>
                    <p class="lead">%s</p>
                    <p class="meta">Generated by Hive CLI &middot; base package <code>%s</code> &middot; %s</p>
                    <div class="flow">
                """.formatted(escape(projectName), escape(basePackage), escape(timestamp)));
        appendFlow(body);
        body.append("    </div>\n  </header>\n");

        body.append("  <section class=\"intro\">\n");
        body.append("""
                    <p>This page shows how <strong>inbound adapters</strong> call <strong>input ports</strong>,
                    <strong>application services</strong> orchestrate the use cases, the <strong>domain</strong>
                    stays framework-free, and <strong>outbound adapters</strong> implement the
                    <strong>output ports</strong> the application requires.</p>
                    <div class="levels">
                      <div class="level"><span class="tag">C1</span> System context — the application and who/what it talks to.</div>
                      <div class="level"><span class="tag">C2</span> Containers — the high-level layers of the hexagon.</div>
                      <div class="level"><span class="tag">C3</span> Components — the Hive building blocks and how they connect.</div>
                    </div>
                """);
        body.append("  </section>\n");

        body.append("  <main class=\"diagrams\">\n");
        if (entries.isEmpty()) {
            body.append("    <p class=\"empty\">No diagrams were generated yet.</p>\n");
        }
        for (DiagramEntry entry : entries) {
            body.append("    <article class=\"diagram\">\n");
            body.append("      <h2>").append(escape(entry.displayName())).append("</h2>\n");
            if (entry.inlineSvg() != null) {
                body.append("      <div class=\"figure\">").append(entry.inlineSvg()).append("</div>\n");
            } else if (entry.imageFileName() != null) {
                body.append("      <div class=\"figure\"><img alt=\"")
                        .append(escape(entry.displayName())).append("\" src=\"")
                        .append(escape(entry.imageFileName())).append("\"></div>\n");
            } else {
                body.append("      <div class=\"figure placeholder\">Diagram not rendered. "
                        + "Run with <code>--render</code> once PlantUML is installed.</div>\n");
            }
            body.append("      <p class=\"source\">Source: <a href=\"")
                    .append(escape(entry.pumlFileName())).append("\">")
                    .append(escape(entry.pumlFileName())).append("</a></p>\n");
            body.append("    </article>\n");
        }
        body.append("  </main>\n");

        body.append("""
                  <footer>
                    <p>Generated by <a href="https://github.com/Sinapsi-Technologies/hive">Hive</a> —
                    structure you can see, architecture you can't accidentally break.</p>
                  </footer>
                </div>
                </body>
                </html>
                """);
        return body.toString();
    }

    private void appendFlow(StringBuilder body) {
        String[][] steps = {
                {"Inbound Adapter", "#E8F3FF", "#0B3D91"},
                {"Input Port", "#EEF7FF", "#1E4E79"},
                {"Application Service", "#F6F0FF", "#4B2E83"},
                {"Domain", "#FFF4E5", "#8A4B00"},
                {"Output Port", "#EFFFF4", "#1B5E20"},
                {"Outbound Adapter", "#F0FFF8", "#006B3C"},
        };
        for (int i = 0; i < steps.length; i++) {
            String[] step = steps[i];
            body.append("      <span class=\"pill\" style=\"background:").append(step[1])
                    .append(";color:").append(step[2]).append(";border-color:").append(step[2])
                    .append("\">").append(escape(step[0])).append("</span>\n");
            if (i < steps.length - 1) {
                body.append("      <span class=\"arrow\">→</span>\n");
            }
        }
    }

    private String css() {
        return """
                :root {
                  --ink: #1c2330; --muted: #5b6472; --line: #e6e9ef; --bg: #f7f8fb; --card: #ffffff;
                }
                * { box-sizing: border-box; }
                body { margin: 0; background: var(--bg); color: var(--ink);
                  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                  line-height: 1.55; }
                .page { max-width: 1040px; margin: 0 auto; padding: 32px 20px 64px; }
                code { background: #eef1f6; padding: 1px 6px; border-radius: 5px; font-size: 0.9em; }
                a { color: #1E4E79; }
                .hero { text-align: center; padding: 28px 20px 8px; }
                .brand { font-weight: 700; letter-spacing: 0.5px; color: var(--muted); }
                .hero h1 { font-size: 2.4rem; margin: 6px 0 4px; }
                .lead { font-size: 1.15rem; color: var(--ink); margin: 0; }
                .meta { color: var(--muted); font-size: 0.9rem; margin: 8px 0 18px; }
                .flow { display: flex; flex-wrap: wrap; justify-content: center; align-items: center;
                  gap: 8px; margin: 14px 0 6px; }
                .pill { padding: 6px 12px; border-radius: 999px; border: 1px solid; font-size: 0.85rem;
                  font-weight: 600; white-space: nowrap; }
                .arrow { color: var(--muted); font-weight: 700; }
                .intro { background: var(--card); border: 1px solid var(--line); border-radius: 14px;
                  padding: 20px 24px; margin: 22px 0; }
                .levels { display: grid; gap: 8px; margin-top: 12px; }
                .level { color: var(--muted); }
                .tag { display: inline-block; min-width: 30px; text-align: center; background: #1E4E79;
                  color: #fff; border-radius: 6px; font-size: 0.75rem; font-weight: 700; padding: 2px 6px;
                  margin-right: 6px; }
                .diagrams { display: grid; gap: 24px; }
                .diagram { background: var(--card); border: 1px solid var(--line); border-radius: 14px;
                  padding: 20px 24px; box-shadow: 0 1px 2px rgba(16,24,40,0.04); }
                .diagram h2 { margin: 0 0 14px; font-size: 1.25rem; }
                .figure { overflow: auto; text-align: center; }
                .figure svg, .figure img { max-width: 100%; height: auto; }
                .placeholder { color: var(--muted); border: 1px dashed var(--line); border-radius: 10px;
                  padding: 28px; }
                .source { color: var(--muted); font-size: 0.9rem; margin: 12px 0 0; }
                .empty { color: var(--muted); text-align: center; }
                footer { text-align: center; color: var(--muted); font-size: 0.9rem; margin-top: 40px; }
                """;
    }

    private String escape(String value) {
        if (value == null) {
            return "";
        }
        return value.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;");
    }
}
